spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jpa.open-in-view=false

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
spring.mvc.log-request-details=true

pipeline.crawl.from=1
pipeline.crawl.to=10
pipeline.match.limit=500
pipeline.match.onlyActive=true
pipeline.events.limit=800

pipeline.cron=0 10 6,18 * * *
pipeline.dev.fixedDelayMs=60000